site_name: mkapi
site_url: https://mkapi.daizutabi.net/
site_description: API documentation with MkDocs.
site_author: daizutabi
site_dir: ../mkapi-site/site

repo_url: https://github.com/daizutabi/mkapi/
edit_uri: ""

theme: ivory

plugins:
  - search
  - pheasant:
      version: pheasant

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
