site_name: MkApi
site_url: https://mkapi.daizutabi.net/
site_description: API documentation with MkDocs.
site_author: daizutabi
site_dir: ../mkapi-site/site

repo_url: https://github.com/daizutabi/mkapi/
edit_uri: ""

theme:
  name: ivory
  highlightjs: true
  hljs_languages:
    - yaml

plugins:
  - search
  - pheasant:
      version: mkapi
  - mkapi:
      src_dirs: [examples]

nav:
  - index.md
  - Examples:
    - google_style.md
    - numpy_style.md
  - Advanced Usage:
    - options.md
    - library.py
    - type.py
  - API: mkapi/api/mkapi

markdown_extensions:
  - admonition
  - pymdownx.arithmatex

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
