site_name: MkApi
site_url: https://github.com/daizutabi/mkapi/
site_description: API documentation with MkDocs.
site_author: daizutabi
site_dir: ../mkapi-site

repo_url: https://github.com/daizutabi/mkapi/
edit_uri: ""

theme: readthedocs

plugins:
  - search
  - mkapi:
      api_dir: api
      src_dir: examples

nav:
  - MkApi Documentation: index.md
  # - API: mkapi:mkapi

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
