site_name: MkApi
site_url: https://github.com/daizutabi/mkapi/
site_description: API documentation with MkDocs.
site_author: daizutabi
site_dir: ../mkapi-site

repo_url: https://github.com/daizutabi/mkapi/
edit_uri: ""

extra_css: [extra.css]

theme: readthedocs

plugins:
  - search
  - pheasant
  - mkapi:
      src_dir: examples
      api_dir: api

nav:
  - MkApi Demo: index.md
  # - API: mkapi:mkapi

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
