site_name: mkapi
site_url: https://github.com/daizutabi/mkapi/
site_description: API documentation with MkDocs.
site_author: daizutabi
site_dir: ../mkapi-site

repo_url: https://github.com/daizutabi/mkapi/
edit_uri: ""

theme: ivory

plugins:
  - search
  - mkapi:
      autoapi_dirs: [examples]

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
